K=[...'f999f26227f1f8ff1f1f99f11f8f1ff8f9ff1244f9f9ff9f1ff9f99e9e9ef888fe999ef8f8ff8f880'].map(d=>parseInt(d,16)*16).concat(T=Array(4016).fill(S=B=D=P=E=I=0));
V=new Uint8Array(16);
M=T.slice(0,2048);
K.splice(H=512,0,...[...atob(location.search.slice(1))].map(d=>d.charCodeAt``));
F=onkeyup=_=>{i='x123qweasdzc4rfv'.indexOf(_.key);G[i]=0;P&&(V[x]=i,P=0)};
G=onkeydown=_=>G['x123qweasdzc4rfv'.indexOf(_.key)]=1;
setInterval(_=>{
    for(L=9;L--;
        P||(
            [
                _=>224==O?M=T.slice(0,2048):238==O&&(H=F[--E]),
                _=>H=Q,
                _=>(F[E++]=H,H=Q),
                _=>V[x]==R&&(H+=2),
                _=>V[x]^R&&(H+=2),
                _=>V[x]==V[y]&&(H+=2),
                _=>V[x]=R,
                _=>V[x]=R+V[x],
                _=>[
                    _=>V[x]=V[y],
                    _=>V[x]|=V[y],
                    _=>V[x]&=V[y],
                    _=>V[x]^=V[y],
                    _=>V[15]=+((V[x]+=V[y])>255),
                    _=>(V[15]=+(V[x]>V[y]),V[x]-=V[y]),
                    _=>(V[15]=V[x]&1,V[x]/=2),
                    _=>(V[15]=+(V[y]>V[x]),V[x]=V[y]-V[x]),
                    ,,,,,,
                    _=>(V[15]=+(V[x]&128),V[x]*=2)
                ][z]``,
                _=>V[x]^V[y]&&(H+=2),
                _=>I=Q,
                _=>H=Q+V[0],
                _=>V[x]=(new Date%255)&R,
                _=>{
                    V[15]=0;
                    K.slice(I,z+I).map((a,b)=>{
                        for(j=0;8>j;j++)(a&128)>0&&(x0=V[x]+j,y0=V[y]+b,loc=(0>x0?x0+64:x0%64)+64*(0>y0?y0+32:y0%32),M[loc]^=1,M[loc]||(V[15]=1)),a<<=1
                    })
                },
                _=>R==158?G[V[x]]&&(H+=2):G[V[x]]||(H+=2),
                _=>({
                    7:_=>V[x]=B,
                    10:_=>P=1,
                    21:_=>B=V[x],
                    24:_=>{D=V[x];A=new AudioContext,S=A.createOscillator``,S.connect(A.destination),S.start``},
                    30:_=>I+=V[x],
                    41:_=>I=5*V[x],
                    51:_=>K.splice(I,3,...[...(''+V[x]).padStart(3,0)].map(d=>+d)),
                    85:_=>{for(i=0;i<=x;)K[I+i]=V[i++]},
                    101:_=>{for(i=0;i<=x;)V[i]=K[I+i++]}
                }[R]``)
            ][O>>12]``
        )
    )
        O=K[H]<<
        8|K[H+1],x=(O>>8)&15,y=(O>>4)&15,z=O&15,R=O&255,Q=O&4095,H+=2;
    c=_=>_+_&&[_.splice(0,64).map(d=>d?'░░':'██').join``,...c(_)];
    document.body.innerHTML='<pre>'+c([...M]).join`\n`;
    B&&B--;
    D?D--:S&&S.stop``
},16)
